version: "3.8"

services:
  musicbot:
    image: ghcr.io/deanyo/dannythedj:latest
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      GUILD_ID: ${GUILD_ID}
    restart: unless-stopped
