version: "3.8"

services:
  musicbot:
    image: ghcr.io/deanyo/dannythedj:${IMAGE_TAG:-latest}
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      GUILD_ID: ${GUILD_ID}
      LOG_LEVEL: ${LOG_LEVEL}
    restart: unless-stopped
